### ISSUE TITLE
Change Fingerprint

### ISSUE THREAD

**Issue by h0sch180** [TALUAtGitHub/android_device_samsung_gtaxlwifi#1]
Hi 
use this fingerprint instead of the Xiaomi:

`PRIVATE_BUILD_DESC="gtaxlwifixx-user 8.1.0 M1AJQ T580XXS5CTD1 release-keys"`
`BUILD_FINGERPRINT := samsung/gtaxlwifixx/gtaxlwifi:8.1.0/M1AJQ/T580XXS5CTD1:user/release-keys`

**Comment by TALUAtGitHub** [comment]
Hi,
Sorry for not replying for a while. I've only just noticed this issue.

We use the Xiaomi build fingerprint so that safetynet attestation succeeds. With a build fingerprint from the stock Android 8.1 firmware, safetynet attestation will fail due to mismatching security patch levels. With a build fingerprint from the stock Android 7.0 firmware, safetynet attestation will fail due to mismatching architectures (32-bit ARM vs 64-bit ARM).

I could change the build fingerprint and let users change the build fingerprint themselves to one with which safetynet attestation succeeds, but I'd get some complaints for the inconvenience of having to change it.

**Comment by h0sch180** [comment]
Ah ok I understand, so I think it's better you use your one and ignore my fingerprint.
Thanks and have a nice weekend.

**Comment by TALUAtGitHub** [comment]
Alright, you're welcome. You too.
